### ISSUE TITLE
nm-applet does not show anymore

### ISSUE THREAD

**Issue by lf-araujo** [avahe-kellenberger/nimdow#192]
**Describe the bug**
Ok, long user of this software. Many thanks for this. I don't update too often as it works as intended. In last update, it stopped showing nm-applet at the bar.

**To Reproduce**

```
[autostart]
exec = [
  "xsetroot -cursor_name left_ptr",
  "nm-applet",
  "picom --experimental-backends",
  "synapse",
  # "/home/luis/.config/nimdow/volume.sh",
  "/home/luis/.config/nimdow/date.sh",
  "feh --bg-fill ~/Pictures/wallpaper.jpeg",
  "alacritty -e neo -a -m 'WELCOME BACK'"
]
```

**Expected behavior**
That sweet network indication at the top does not show anymore :(

- What am I doing wrong?

**Comment by avahe-kellenberger** [comment]
I'm on the most recent commit and tried this out, and the network manager applet is showing.

1. Can you show the output of `nimdow -v`
2. I'd also like to see your whole config file if that's alright

Glad you've been enjoying Nimdow! Hope to hear back so I can help get the issue resolved. It may be something unrelated to Nimdow, however

**Comment by lf-araujo** [comment]
Sure, thanks:

![image](https://user-images.githubusercontent.com/10139950/149151710-910875e3-1791-4fde-8875-b7d8937249b4.png)

```toml
# Start external programs

[[startProcess]]
command = "pkill nimdow"
keys = [ "Delete" ]
modifiers = [ "control", "alt" ]

[[startProcess]]
command = "firefox"
keys = [ "i" ]
modifiers = [ "super" ]

[[startProcess]]
command = "alacritty"
keys = [ "Return" ]
modifiers = [ "super" ]

[autostart]
exec = [
  "xsetroot -cursor_name left_ptr",
  "nm-applet",
  "picom --experimental-backends",
  "synapse",
  # "/home/luis/.config/nimdow/volume.sh",
  "/home/luis/.config/nimdow/date.sh",
  "feh --bg-fill ~/Pictures/wallpaper.jpeg"
]

[settings]
  # Window settings
  gapSize = 12
  borderWidth = 1
  borderColorUnfocused = "#282a36"
  borderColorFocused = "#50fa7b"
  borderColorUrgent = "#ff5555"
  # Bar settings
  barHeight = 30
  barBackgroundColor = "#282a36"
  barForegroundColor = "#f8f8f2"
  barSelectionColor = "#50fa7b"
  barUrgentColor = "#ff5555"
  barFonts = [
    "monospace:size=10:anialias=false",
    "FiraCode Nerd Font:size=10:anialias=false"
  ]
  # General settings
  loggingEnabled = false

# Window manager controls
[controls]
  [controls.reloadConfig]
  keys = [ "r" ]
  modifiers = [ "super", "shift" ]

  [controls.focusPrevious]
  keys = [ "k" ]
  modifiers = [ "super" ]

  [controls.focusNext]
  keys = [ "j" ]
  modifiers = [ "super" ]

  [controls.moveWindowPrevious]
  keys = [ "k" ]
  modifiers = [ "super", "shift" ]

  [controls.moveWindowNext]
  keys = [ "j" ]
  modifiers = [ "super", "shift" ]

  [controls.toggleFullscreen]
  keys = [ "f" ]
  modifiers = [ "super" ]

  [controls.destroySelectedWindow]
  keys = [ "d" ]
  modifiers = [ "super" ]

  [controls.moveWindowToTag]
  keys = [ "1", "2", "3", "4", "5", "6", "7", "8", "9" ]
  modifiers = [ "super", "shift" ]

  [controls.goToTag]
  keys = [ "1", "2", "3", "4", "5", "6", "7", "8", "9" ]
  modifiers = [ "super" ]

  [controls.goToPreviousTag]
  keys = [ "w" ]
  modifiers = [ "super" ]

  [controls.toggleTagView]
  keys = [ "1", "2", "3", "4", "5", "6", "7", "8", "9" ]
  modifiers = [ "super", "control" ]

  [controls.toggleWindowTag]
  keys = [ "1", "2", "3", "4", "5", "6", "7", "8", "9" ]
  modifiers = [ "super", "shift", "control" ]

  [controls.focusPreviousMonitor]
  keys = [ "comma" ]
  modifiers = [ "super" ]

  [controls.focusNextMonitor]
  keys = [ "period" ]
  modifiers = [ "super" ]

  [controls.moveWindowToPreviousMonitor]
  keys = [ "comma" ]
  modifiers = [ "super", "shift" ]

  [controls.moveWindowToNextMonitor]
  keys = [ "period" ]
  modifiers = [ "super", "shift" ]

  [controls.increaseMasterCount]
  keys = [ "z" ]
  modifiers = [ "super" ]

  [controls.decreaseMasterCount]
  keys = [ "x" ]
  modifiers = [ "super" ]

  [controls.toggleFloating]
  keys = [ "space" ]
  modifiers = [ "super" ]

  [controls.jumpToUrgentWindow]
  keys = [ "u" ]
  modifiers = [ "super" ]
```
