### ISSUE TITLE
Allow for `[[startProcess]]` blocks without `modifiers` array

### ISSUE THREAD

**Issue by avahe-kellenberger** [avahe-kellenberger/nimdow#194]
In some cases such as `XF86MonBrightnessUp`, the user does not want to press super, alt, ctrl etc.

The following block should work with `modifiers` commented out:

```toml
[[startProcess]]
command = "notify-send 'brightness up'"
keys = [ "XF86MonBrightnessUp" ]
# modifiers = [ "super" ]
```
#193
