### ISSUE TITLE
Option to disable or hide bar

### ISSUE THREAD

**Issue by Visone-Selektah** [avahe-kellenberger/nimdow#196]
Hi!
I'm an user of dwm and spectrwm, both without bars, it would be fine to have that option in nimdow.

Thanks for your work!!!!

**Comment by grazzhopper** [comment]
I would love to see an option to toggle the topbar also. My dwm xsetroot for the topbar worked out of the box.
Love your work!

**Comment by avahe-kellenberger** [comment]
I'll prioritize this; thanks for your feedback

**Comment by avahe-kellenberger** [comment]
Partially implemented in v0.7.32 - you can hide the bar with a new control

Default:
```toml
[controls.toggleStatusBar]
  keys = [ "b" ]
  modifiers = [ "super" ]
```

or,  using the cli:

`nimdow --toggle-statusbar`
