### ISSUE TITLE
Support for assigning class and their instances to tags

### ISSUE THREAD

**Issue by dakyskye** [avahe-kellenberger/nimdow#52]
I am not really familiar with tagging system, but as a guy who used workspaces for months, I would like to assign some applications to certain tags by their class. This is useful if you start a couple of GUI/TUI applications at login, because if you don't assign them to tags, they will get launched in the same tag, and would be a mess! So, for example, this should do the job in the config file:
```toml
[[appRule]] # every class of Alacritty
class = 'Alacritty'
instance = ''

[appRule.assignment]
monitor = 1
tag = 3

[[appRule]] # cordless instance of Alacritty, overrides above ^
class = 'Alacritty'
instance = 'cordless'

[appRule.assignment]
monitor = 1
tag = 4

[[appRule]]
class = 'firefoxdeveloperedition'
instance = ''

[appRule.assignment]
monitor = 0
tag = 1
```

**Comment by dakyskye** [comment]
Again, that maybe relevant to workspace system, but would be cool to have it in Nimdow!

**Comment by dakyskye** [comment]
Titles should also be supported, because AFAIK instance and title may not match, and that makes sense.

I am self assigning this issue.

**Comment by avahe-kellenberger** [comment]
One note, we should have it be `tags` and an array of tag numbers

**Comment by avahe-kellenberger** [comment]
Another note, when talking to another user, they want to be able to sen a window as floating in a similar fashion.
Should have an option for class and name.

**Comment by PMunch** [comment]
With some windows assigned to tags this way it may also make sense to be able to configure the default number of masters on a per-tag basis.

**Comment by avahe-kellenberger** [comment]
@avahe-kellenberger Self ping - combine with #68, but use the method daky suggested in this issue.

**Comment by avahe-kellenberger** [comment]
@dakyskye What was your intention for `instance`, do you mean `_NET_WM_NAME`?

**Comment by dakyskye** [comment]
The instance is the first value of `WM_CLASS`. For example: `WM_CLASS(STRING) = "cordless", "Alacritty"` means it's an instance of Alacritty class called `cordless`. So this can be useful when you want Nimdow to assign `cordless` to certain tag. The other way would be using WM title, but I'd prefer a terminal instance called cordless.

**Comment by avahe-kellenberger** [comment]
@dakyskye I was thinking of doing something like this:

```toml
[[appRule]] # every class of Alacritty
class = 'Alacritty'
monitor = 2
tags = [ 3, 4 ]

[[appRule]] # cordless instance of Alacritty, overrides above ^
class = 'Alacritty'
instance = 'cordless'
monitor = 2
tags = [ 4 ]

[[appRule]]
class = 'firefoxdeveloperedition'
monitor = 1
tags = [ 1 ]
```

Unless there was a reason to have an `appRule` *and*  `appRule.assignment`. Thoughts?
