### ISSUE TITLE
Easier configuration for status bar

### ISSUE THREAD

**Issue by dakyskye** [avahe-kellenberger/nimdow#56]
Probably, define status bar commands etc. stuff in config file, or have a separate program (or command line argument) like `dwmblocks` or `i3blocks` to config it easier. An example config:
```toml
separator = ' | '

[[modules]]
name = 'kernel'
prefix = ' '

[modules.label]
text = ''

[modules.label.command]
cmd = 'uname -r | cut -c1-5'
interval = 0

[[modules]]
name = 'updates'
prefix = ' '

[modules.label]
text = ''

[modules.label.command]
cmd = 'pacman -Qu | wc -l'
interval = 1000

[[modules]]
name = 'custom text'
prefix = ''

[modules.label]
text = 'my custom text!'

[modules.label.command]
```
