### ISSUE TITLE
Nimdow crashes when refreshed with a bad config

### ISSUE THREAD

**Issue by PMunch** [avahe-kellenberger/nimdow#93]
**Describe the bug**
I wanted to set up shortcuts for my music player for the media keys on my keyboard. Since they wouldn't need modifier keys I defined them without a `modifier` array in the TOML file. When I refreshed nimdow it crashed and dropped me back to the shell. It would be nice if nimdow would check the config before changing and somehow show an error if the config isn't correctly formatted, similar to how i3 does it.

**To Reproduce**
1. Create an invalid config, e.g.:
``` toml
[[startProcess]]
command = "audacious --fwd"
keys = ["XF86AudioNext"]
# Notice the lack of modifiers array
```
2. Reload the config

**Expected behavior**
Some kind of error message pop-up telling me that the config was broken and that it didn't switch to it.
